// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package registry

import (
	"in-gravity/applications"
	"in-gravity/infrastructures/mysql/repositories"
)

// Injectors from application.go:

func ProvideCreateUserApplicationService(p applications.CreateUserPresenterInterface) (applications.CreateUserApplicationServiceInterface, error) {
	userRepositoryInterface := repositories.NewUserRepository()
	createUserApplicationServiceInterface := applications.NewCreateUserApplicationService(p, userRepositoryInterface)
	return createUserApplicationServiceInterface, nil
}
